# Site settings
title: Nicolas Brugneaux, developer in Berlin
email: nicolas.brugneaux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Nicolas Brugneaux, I am a French developer based in Berlin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nicolasbrugneaux.me" # the base hostname & protocol for your site
twitter_username: nbrugneaux
github_username:  nicolasbrugneaux

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination settings

# Posts settings
permalink: pretty
future: true

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# Navigation
nav:
  - label: Coding
    url: /projects/
  - label: About
    url: /about/
